In [1]:
import pandas as pd 
import numpy as np 
import itertools 

pd.options.mode.chained_assignment = None

In [29]:
pd.options.mode.chained_assignment = None # default='warn'

In [10]:
df1 = pd.read_csv('df_segment_1.csv') 
df1

,Абсолютная маржа_buyed,Маржа_buyed,Средняя маржа_buyed,Средний чек_buyed,Кол-во чеков_buyed,Кол-во товаров_buyed,Среднее кол-во товаров в чеке_buyed,Кол-во уникальных клиентов_buyed,Ценность клиента_buyed,Количество_all,...,ДЕТСКОЕ_ПИТАНИЕ,ТЕХНИКА_И_ТОВАРЫ_ДЛЯ_ДОМА,ТОВАРЫ_ДЛЯ_ЖИВОТНЫХ,ИнтернетДоставка,Калуга,Москва,Ростов_на_Дону,Саратов,Другой,Labels
0,1262,0.312531,631.000000,2636,2,18,9,1,1262,19,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
1,3208,0.439272,802.000000,1862,4,6,2,1,3208,6,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
2,612,0.460497,306.000000,664,2,9,4,1,612,9,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
3,2567,0.191481,855.666667,4469,3,10,3,1,2567,10,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
4,3016,0.570672,1508.000000,2642,2,9,4,1,3016,11,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7459,1871,0.906053,1871.000000,2214,1,4,4,1,1871,35,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0
7460,625,0.730994,625.000000,904,1,9,9,1,625,45,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0
7461,801,0.910227,801.000000,929,1,1,1,1,801,10,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
7462,2932,0.977333,2932.000000,3049,1,1,1,1,2932,40,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
7463,1407,0.858974,1407.000000,1737,1,4,4,1,1407,24,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0

In [12]:
df2 = pd.read_csv('df_segment_2.csv')

In [13]:
df3 = pd.read_csv('df_segment_3.csv')

In [14]:
df4 = pd.read_csv('df_segment_4.csv')

In [84]:
pd.set_option('display.max_columns', None)

In [85]:
df4

,Абсолютная маржа_buyed,Маржа_buyed,Средняя маржа_buyed,Средний чек_buyed,Кол-во чеков_buyed,Кол-во товаров_buyed,Среднее кол-во товаров в чеке_buyed,Кол-во уникальных клиентов_buyed,Ценность клиента_buyed,Количество_all,Абсолютная маржа_all,Маржа_all,Средняя маржа_all,Кол-во чеков_all,Кол-во товаров_all,Кол-во уникальных клиентов_all,Ценность клиента_all,Количество_all.1,КРУПНОГАБАРИТНЫЙ_ТОВАР,ТЕКСТИЛЬ_ТРИКОТАЖ,ОБУВЬ,КАНЦТОВАРЫ_КНИГИ_ДИСКИ,ТОВАРЫ_ДЛЯ_КОРМЛЕНИЯ,ИГРУШКИ,КОСМЕТИКА_ГИГИЕНА,СОПУТСТВУЮЩИЕ_ТОВАРЫ,ЖЕНСКИЕ_ШТУЧКИ,ПОДГУЗНИКИ,ДЕТСКОЕ_ПИТАНИЕ,ТЕХНИКА_И_ТОВАРЫ_ДЛЯ_ДОМА,ТОВАРЫ_ДЛЯ_ЖИВОТНЫХ,ИнтернетДоставка,Калуга,Москва,Ростов_на_Дону,Саратов,Другой,Labels,Кластер
0,2891,0.365487,2891.000000,7910,1,2,2,1,2891,2,2891,0.365487,2891.000000,1,2,1,2891,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3,4
1,6359,0.386942,2119.666667,5478,3,5,2,1,6359,5,6359,0.386942,2119.666667,3,5,1,6359,5,0.8,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3,4
2,3150,0.594452,3150.000000,5299,1,1,1,1,3150,1,3150,0.594452,3150.000000,1,1,1,3150,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3,4
3,4651,0.387907,4651.000000,11990,1,1,1,1,4651,1,4651,0.387907,4651.000000,1,1,1,4651,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3,4
4,5456,0.441781,5456.000000,12350,1,1,1,1,5456,1,5456,0.441781,5456.000000,1,1,1,5456,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4236,4124,0.249955,4124.000000,16499,1,1,1,1,4124,1,4124,0.249955,4124.000000,1,1,1,4124,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3,4
4237,2999,0.230710,2999.000000,13098,1,1,1,1,2999,1,2999,0.230710,2999.000000,1,1,1,2999,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3,4
4238,2784,0.368693,2784.000000,7700,1,1,1,1,2784,1,2784,0.368693,2784.000000,1,1,1,2784,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3,4
4239,4384,0.848626,4384.000000,5215,1,1,1,1,4384,6,4384,0.848626,4384.000000,1,1,1,4384,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3,4
4240,5675,0.936469,2837.500000,3129,2,2,1,1,5675,30,5675,0.936469,2837.500000,2,2,1,5675,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3,4

In [87]:
df1['Кластер'] = 1
df2['Кластер'] = 2
df3['Кластер'] = 3
df4['Кластер'] = 4

df_combined = pd.concat([df1, df2, df3, df4], ignore_index=True)
df_combined.to_excel('segments.xlsx')

In [81]:
df_combined['Labels'].value_counts()

2    23160
1    21154
0     7464
3     4241
Name: Labels, dtype: int64

In [ ]:
df.combined

In [23]:
vitrina = pd.read_csv('vitrina_only_general_info.csv', sep=';') 
vitrina

,Телефон_new,Выручка_buyed,Абсолютная маржа_buyed,Маржа_buyed,Средняя маржа_buyed,Средний чек_buyed,Кол-во чеков_buyed,Кол-во товаров_buyed,Среднее кол-во товаров в чеке_buyed,Кол-во уникальных клиентов_buyed,...,Абсолютная маржа_all,Маржа_all,Средняя маржа_all,Средний чек_all,Кол-во чеков_all,Кол-во товаров_all,Среднее кол-во товаров в чеке_all,Кол-во уникальных клиентов_all,Ценность клиента_all,Количество_all.1
0,55574954-50515053535277,992,435,0.438508,217.5,545,2,3,2,1,...,794,0.271360,264.666667,1023,3,11,4,1,794,12
1,55574954-56545048505170,4038,1262,0.312531,631.0,2636,2,18,9,1,...,1262,0.312531,631.000000,2636,2,18,9,1,1262,19
2,55575349-49505555535574,7910,2891,0.365487,2891.0,7910,1,2,2,1,...,2891,0.365487,2891.000000,7910,1,2,2,1,2891,2
3,55574854-55525053544978,1101,459,0.416894,459.0,1150,1,2,2,1,...,459,0.416894,459.000000,1150,1,2,2,1,459,2
4,55575351-51495656575170,2622,759,0.289474,759.0,2622,1,6,6,1,...,759,0.289474,759.000000,2622,1,6,6,1,759,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60638,55574949-57565751545277,1399,500,0.357398,500.0,1498,1,1,1,1,...,500,0.357398,500.000000,1498,1,1,1,1,500,1
60639,55574854-55505648555577,1616,1423,0.880569,1423.0,1665,1,1,1,1,...,1423,0.880569,1423.000000,1665,1,1,1,1,1423,8
60640,55575053-50544856505076,3220,1480,0.459627,1480.0,3269,1,4,4,1,...,1480,0.459627,1480.000000,3269,1,4,4,1,1480,4
60641,55575054-55574849485475,225,86,0.382222,86.0,274,1,1,1,1,...,86,0.382222,86.000000,274,1,1,1,1,86,1
60642,55575054-50575353565477,2988,1550,0.518742,1550.0,3037,1,1,1,1,...,1550,0.518742,1550.000000,3037,1,1,1,1,1550,2

In [32]:
data = pd.read_csv('for_tables_filtered_data_Размещенные.csv', sep=';') 
data

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,...,ID_SKU,ГородМагазина,МагазинЗаказа,Нов_СуммаЗаказаНаСайте,Нов_СуммаСтроки,Нов_Маржа,Дата_дата,ДеньНеделиЦифра,ВремяОкругл,ДеньНедели
0,01.05.2017 0:03,03.05.2017 0:00,4513479_TR,Доставлен,761,761.0,Магазины,Безналичная,Москва,КРУПНОГАБАРИТНЫЙ ТОВАР,...,ID10020734553,ИнтернетДоставка,NaN,761.0,152.0,76.00,2017-01-05,3,0,Четверг
1,01.05.2017 10:18,03.05.2017 0:00,4513492_TR,К отгрузке,1 878,1878.0,Pick point,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,IDL00035982755,ИнтернетДоставка,NaN,1878.0,499.0,199.00,2017-01-05,3,10,Четверг
2,01.05.2017 15:27,08.05.2017 0:00,4513472_TR,К отгрузке,9 693,9693.0,Курьерская,Наличная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,IDL00028785351,ИнтернетДоставка,NaN,9693.0,678.2,316.77,2017-01-05,3,15,Четверг
3,01.05.2017 15:27,08.05.2017 0:00,4513472_TR,К отгрузке,9 693,9693.0,Курьерская,Наличная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,IDL00000992250,ИнтернетДоставка,NaN,9693.0,89.0,51.00,2017-01-05,3,15,Четверг
4,01.05.2017 15:27,08.05.2017 0:00,4513472_TR,К отгрузке,9 693,9693.0,Курьерская,Наличная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,IDL00044965452,ИнтернетДоставка,NaN,9693.0,1080.0,505.20,2017-01-05,3,15,Четверг
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435664,30.06.2017 22:55,04.07.2017 0:00,5031477_TR,Доставлен,3 416,3416.0,Магазины,Безналичная,Москва,ДЕТСКОЕ ПИТАНИЕ,...,IDL00007784452,ИнтернетДоставка,NaN,3416.0,490.0,431.04,2017-06-30,4,22,Пятница
435665,30.06.2017 22:55,04.07.2017 0:00,5031477_TR,Доставлен,3 416,3416.0,Магазины,Безналичная,Москва,ДЕТСКОЕ ПИТАНИЕ,...,IDL00017315452,ИнтернетДоставка,NaN,3416.0,198.0,99.50,2017-06-30,4,22,Пятница
435666,30.06.2017 23:13,11.07.2017 0:00,5031575_TR,К отгрузке,6 690,6690.0,Pick point,Безналичная,Санкт-Петербург,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,IDL00051785149,ИнтернетДоставка,NaN,6690.0,199.0,103.00,2017-06-30,4,23,Пятница
435667,30.06.2017 23:58,06.07.2017 0:00,5031783_TR,Доставлен,2 819,2819.0,Магазины,Безналичная,Нижний Новгород,ДЕТСКОЕ ПИТАНИЕ,...,ID000sm-0652654,ИнтернетДоставка,NaN,2819.0,336.0,252.10,2017-06-30,4,23,Пятница
435668,30.06.2017 23:58,06.07.2017 0:00,5031783_TR,Доставлен,2 819,2819.0,Магазины,Безналичная,Нижний Новгород,ДЕТСКОЕ ПИТАНИЕ,...,ID000sm-0652452,ИнтернетДоставка,NaN,2819.0,168.0,84.10,2017-06-30,4,23,Пятница

In [35]:
# Фильтрация строк, где НовыйСтатус = "доставлен"
data_filtered = data[data['НовыйСтатус'] == 'Доставлен']

# Вывод первых нескольких строк отфильтрованного датасета
data_filtered

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,...,ID_SKU,ГородМагазина,МагазинЗаказа,Нов_СуммаЗаказаНаСайте,Нов_СуммаСтроки,Нов_Маржа,Дата_дата,ДеньНеделиЦифра,ВремяОкругл,ДеньНедели
0,01.05.2017 0:03,03.05.2017 0:00,4513479_TR,Доставлен,761,761.0,Магазины,Безналичная,Москва,КРУПНОГАБАРИТНЫЙ ТОВАР,...,ID10020734553,ИнтернетДоставка,NaN,761.0,152.0,76.00,2017-01-05,3,0,Четверг
10,01.05.2017 2:09,03.05.2017 0:00,4513502_TR,Доставлен,3 299,3234.0,Магазины,Безналичная,Красногорск (Красногорский район),КРУПНОГАБАРИТНЫЙ ТОВАР,...,ID59320856,ИнтернетДоставка,NaN,3234.0,1235.0,605.00,2017-01-05,3,2,Четверг
17,01.05.2017 2:09,13.05.2017 0:00,4513529_TR,Доставлен,7 910,7910.0,Магазины,Безналичная,Челябинск,КРУПНОГАБАРИТНЫЙ ТОВАР,...,ID9010025983048,ИнтернетДоставка,NaN,7910.0,5820.0,1935.00,2017-01-05,3,2,Четверг
18,01.05.2017 2:09,13.05.2017 0:00,4513529_TR,Доставлен,7 910,7910.0,Магазины,Безналичная,Челябинск,КРУПНОГАБАРИТНЫЙ ТОВАР,...,IDL00000795856,ИнтернетДоставка,NaN,7910.0,2090.0,956.00,2017-01-05,3,2,Четверг
19,01.05.2017 2:09,04.05.2017 0:00,4513533_TR,Доставлен,1 830,1150.0,Магазины,Безналичная,Москва,КРУПНОГАБАРИТНЫЙ ТОВАР,...,IDL00007294553,ИнтернетДоставка,NaN,1150.0,461.0,182.61,2017-01-05,3,2,Четверг
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435663,30.06.2017 22:55,04.07.2017 0:00,5031477_TR,Доставлен,3 416,3416.0,Магазины,Безналичная,Москва,ДЕТСКОЕ ПИТАНИЕ,...,IDL00017315250,ИнтернетДоставка,NaN,3416.0,198.0,99.50,2017-06-30,4,22,Пятница
435664,30.06.2017 22:55,04.07.2017 0:00,5031477_TR,Доставлен,3 416,3416.0,Магазины,Безналичная,Москва,ДЕТСКОЕ ПИТАНИЕ,...,IDL00007784452,ИнтернетДоставка,NaN,3416.0,490.0,431.04,2017-06-30,4,22,Пятница
435665,30.06.2017 22:55,04.07.2017 0:00,5031477_TR,Доставлен,3 416,3416.0,Магазины,Безналичная,Москва,ДЕТСКОЕ ПИТАНИЕ,...,IDL00017315452,ИнтернетДоставка,NaN,3416.0,198.0,99.50,2017-06-30,4,22,Пятница
435667,30.06.2017 23:58,06.07.2017 0:00,5031783_TR,Доставлен,2 819,2819.0,Магазины,Безналичная,Нижний Новгород,ДЕТСКОЕ ПИТАНИЕ,...,ID000sm-0652654,ИнтернетДоставка,NaN,2819.0,336.0,252.10,2017-06-30,4,23,Пятница
435668,30.06.2017 23:58,06.07.2017 0:00,5031783_TR,Доставлен,2 819,2819.0,Магазины,Безналичная,Нижний Новгород,ДЕТСКОЕ ПИТАНИЕ,...,ID000sm-0652452,ИнтернетДоставка,NaN,2819.0,168.0,84.10,2017-06-30,4,23,Пятница

In [38]:
dt = data_filtered[data_filtered["Телефон_new"] != "0"] 
dt

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,...,ID_SKU,ГородМагазина,МагазинЗаказа,Нов_СуммаЗаказаНаСайте,Нов_СуммаСтроки,Нов_Маржа,Дата_дата,ДеньНеделиЦифра,ВремяОкругл,ДеньНедели
0,01.05.2017 0:03,03.05.2017 0:00,4513479_TR,Доставлен,761,761.0,Магазины,Безналичная,Москва,КРУПНОГАБАРИТНЫЙ ТОВАР,...,ID10020734553,ИнтернетДоставка,NaN,761.0,152.0,76.00,2017-01-05,3,0,Четверг
10,01.05.2017 2:09,03.05.2017 0:00,4513502_TR,Доставлен,3 299,3234.0,Магазины,Безналичная,Красногорск (Красногорский район),КРУПНОГАБАРИТНЫЙ ТОВАР,...,ID59320856,ИнтернетДоставка,NaN,3234.0,1235.0,605.00,2017-01-05,3,2,Четверг
17,01.05.2017 2:09,13.05.2017 0:00,4513529_TR,Доставлен,7 910,7910.0,Магазины,Безналичная,Челябинск,КРУПНОГАБАРИТНЫЙ ТОВАР,...,ID9010025983048,ИнтернетДоставка,NaN,7910.0,5820.0,1935.00,2017-01-05,3,2,Четверг
18,01.05.2017 2:09,13.05.2017 0:00,4513529_TR,Доставлен,7 910,7910.0,Магазины,Безналичная,Челябинск,КРУПНОГАБАРИТНЫЙ ТОВАР,...,IDL00000795856,ИнтернетДоставка,NaN,7910.0,2090.0,956.00,2017-01-05,3,2,Четверг
19,01.05.2017 2:09,04.05.2017 0:00,4513533_TR,Доставлен,1 830,1150.0,Магазины,Безналичная,Москва,КРУПНОГАБАРИТНЫЙ ТОВАР,...,IDL00007294553,ИнтернетДоставка,NaN,1150.0,461.0,182.61,2017-01-05,3,2,Четверг
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435663,30.06.2017 22:55,04.07.2017 0:00,5031477_TR,Доставлен,3 416,3416.0,Магазины,Безналичная,Москва,ДЕТСКОЕ ПИТАНИЕ,...,IDL00017315250,ИнтернетДоставка,NaN,3416.0,198.0,99.50,2017-06-30,4,22,Пятница
435664,30.06.2017 22:55,04.07.2017 0:00,5031477_TR,Доставлен,3 416,3416.0,Магазины,Безналичная,Москва,ДЕТСКОЕ ПИТАНИЕ,...,IDL00007784452,ИнтернетДоставка,NaN,3416.0,490.0,431.04,2017-06-30,4,22,Пятница
435665,30.06.2017 22:55,04.07.2017 0:00,5031477_TR,Доставлен,3 416,3416.0,Магазины,Безналичная,Москва,ДЕТСКОЕ ПИТАНИЕ,...,IDL00017315452,ИнтернетДоставка,NaN,3416.0,198.0,99.50,2017-06-30,4,22,Пятница
435667,30.06.2017 23:58,06.07.2017 0:00,5031783_TR,Доставлен,2 819,2819.0,Магазины,Безналичная,Нижний Новгород,ДЕТСКОЕ ПИТАНИЕ,...,ID000sm-0652654,ИнтернетДоставка,NaN,2819.0,336.0,252.10,2017-06-30,4,23,Пятница
435668,30.06.2017 23:58,06.07.2017 0:00,5031783_TR,Доставлен,2 819,2819.0,Магазины,Безналичная,Нижний Новгород,ДЕТСКОЕ ПИТАНИЕ,...,ID000sm-0652452,ИнтернетДоставка,NaN,2819.0,168.0,84.10,2017-06-30,4,23,Пятница

### Количество подкатегорий Группы2. Будут использоваться в качестве названий колонок витрины для Market Basket.

In [41]:
columns = np.unique(dt["Группа2"].values) 
print(columns)

['ДЕТСКОЕ ПИТАНИЕ' 'ЖЕНСКИЕ ШТУЧКИ' 'ИГРУШКИ' 'КАНЦТОВАРЫ, КНИГИ, ДИСКИ'
 'КОСМЕТИКА/ГИГИЕНА' 'КРУПНОГАБАРИТНЫЙ ТОВАР' 'ОБУВЬ' 'ПОДГУЗНИКИ'
 'СОПУТСТВУЮЩИЕ ТОВАРЫ' 'ТЕКСТИЛЬ, ТРИКОТАЖ' 'ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА'
 'ТОВАРЫ ДЛЯ ЖИВОТНЫХ' 'ТОВАРЫ ДЛЯ КОРМЛЕНИЯ']

In [42]:
dt["Группа2"].value_counts()

ИГРУШКИ                      51906
ТЕКСТИЛЬ, ТРИКОТАЖ           44427
ДЕТСКОЕ ПИТАНИЕ              37079
ПОДГУЗНИКИ                   28903
КОСМЕТИКА/ГИГИЕНА            24376
КРУПНОГАБАРИТНЫЙ ТОВАР       17841
ТОВАРЫ ДЛЯ КОРМЛЕНИЯ         16284
КАНЦТОВАРЫ, КНИГИ, ДИСКИ      9625
ОБУВЬ                         6861
ТОВАРЫ ДЛЯ ЖИВОТНЫХ           3743
СОПУТСТВУЮЩИЕ ТОВАРЫ           594
ЖЕНСКИЕ ШТУЧКИ                 539
ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА       85
Name: Группа2, dtype: int64

### Рассмотрим чеки. Собрать из них словарь для индексов.

In [43]:
dt["Телефон_new"].value_counts()

55575450-57565152565479    203
55575053-51535156565077    176
55574850-53545452504975    139
55575057-57555553534877    130
55574954-57484849515770    127
                          ...
55574948-56535648514877      1
55575053-51535349515074      1
55575448-56504952495470      1
55574853-53545555524977      1
55575054-50575353565477      1
Name: Телефон_new, Length: 60643, dtype: int64

In [44]:
checks = np.array(dt["Телефон_new"]) 
checks = np.unique(checks) 

print(len(checks)) 
print(checks)

60643
['55515349-57485148505273' '55515349-57485748544876'
 '55535057-57525455575274' ... '57485453-52545749545698'
 '57485453-54565648545092' '57545549-57544957525799']

In [45]:
checks_loc = {key: i for i, key in enumerate(checks)}

### Создаем витрину с колонками Market Basket.

In [46]:
MB = pd.DataFrame(columns=columns)

### Функция: добавлеет новой строки в таблицу, которая заполнена нулями

In [47]:
def add_row(df): 
    temp = pd.DataFrame(0, index=[i for i in checks], columns=columns) 
    df = df.append(temp, ignore_index=False, sort=False) 
    return df

In [48]:
MB = add_row(MB) 
MB = MB.reset_index() 
MB = MB.rename(columns={"index": "КЛИЕНТ"}) 

MB

/var/folders/sm/yw7wdqkn4jl9qbr7mwdtdxph0000gn/T/ipykernel_84132/3835099181.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp, ignore_index=False, sort=False)

,КЛИЕНТ,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,55515349-57485148505273,0,0,0,0,0,0,0,0,0,0,0,0,0
1,55515349-57485748544876,0,0,0,0,0,0,0,0,0,0,0,0,0
2,55535057-57525455575274,0,0,0,0,0,0,0,0,0,0,0,0,0
3,55545651-57575053555375,0,0,0,0,0,0,0,0,0,0,0,0,0
4,55574848-48484957505771,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60638,56574953-57535556534880,0,0,0,0,0,0,0,0,0,0,0,0,0
60639,56575655-52525750505484,0,0,0,0,0,0,0,0,0,0,0,0,0
60640,57485453-52545749545698,0,0,0,0,0,0,0,0,0,0,0,0,0
60641,57485453-54565648545092,0,0,0,0,0,0,0,0,0,0,0,0,0
60642,57545549-57544957525799,0,0,0,0,0,0,0,0,0,0,0,0,0

In [62]:
MB1 = MB[MB['КЛИЕНТ'] == '0'] 
MB1 
# Фильтрация строк, где Телефон_new не равен "0" и не является NaN
dt = dt[dt["Телефон_new"].notna() & (dt["Телефон_new"] != "0")]

In [61]:
MB.dtypes

КЛИЕНТ                       object
ДЕТСКОЕ ПИТАНИЕ              object
ЖЕНСКИЕ ШТУЧКИ               object
ИГРУШКИ                      object
КАНЦТОВАРЫ, КНИГИ, ДИСКИ     object
КОСМЕТИКА/ГИГИЕНА            object
КРУПНОГАБАРИТНЫЙ ТОВАР       object
ОБУВЬ                        object
ПОДГУЗНИКИ                   object
СОПУТСТВУЮЩИЕ ТОВАРЫ         object
ТЕКСТИЛЬ, ТРИКОТАЖ           object
ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА    object
ТОВАРЫ ДЛЯ ЖИВОТНЫХ          object
ТОВАРЫ ДЛЯ КОРМЛЕНИЯ         object
dtype: object

### Добавление товаров. Построчное добавление количества товара в чек

In [64]:
for i in range(0, len(dt)):  
    check = dt["Телефон_new"].iloc[i] 
    if check in checks_loc:
        j = checks_loc[check]
        
        if dt["Группа2"].iloc[i] not in MB:
            MB[dt["Группа2"].iloc[i]] = {}
        
        if j not in MB[dt["Группа2"].iloc[i]]:
            MB[dt["Группа2"].iloc[i]][j] = 0
        
        MB[dt["Группа2"].iloc[i]][j] += dt["КоличествоПроданоКлиенту"].iloc[i]
    else:
        print(f"Ключ {check} отсутствует в checks_loc")

In [65]:
MB

,КЛИЕНТ,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,55515349-57485148505273,0,0,0,0,0,1,0,0,0,0,0,0,0
1,55515349-57485748544876,0,0,0,0,0,1,0,0,0,0,0,0,0
2,55535057-57525455575274,0,0,0,0,0,0,0,0,0,3,0,0,0
3,55545651-57575053555375,0,0,0,0,0,0,1,0,0,0,0,0,0
4,55574848-48484957505771,0,0,8,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60638,56574953-57535556534880,0,0,0,0,2,0,0,0,0,0,0,0,0
60639,56575655-52525750505484,2,0,0,0,2,0,0,2,0,1,0,0,0
60640,57485453-52545749545698,0,0,0,0,0,0,0,2,0,0,0,0,0
60641,57485453-54565648545092,0,0,0,0,1,0,0,4,0,0,0,0,0
60642,57545549-57544957525799,0,0,0,0,0,1,0,0,0,0,0,0,0

In [66]:
MB.to_csv('MBClient.csv', index=False, sep=';', encoding='utf-8-sig')

In [67]:
MB

,КЛИЕНТ,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,55515349-57485148505273,0,0,0,0,0,1,0,0,0,0,0,0,0
1,55515349-57485748544876,0,0,0,0,0,1,0,0,0,0,0,0,0
2,55535057-57525455575274,0,0,0,0,0,0,0,0,0,3,0,0,0
3,55545651-57575053555375,0,0,0,0,0,0,1,0,0,0,0,0,0
4,55574848-48484957505771,0,0,8,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60638,56574953-57535556534880,0,0,0,0,2,0,0,0,0,0,0,0,0
60639,56575655-52525750505484,2,0,0,0,2,0,0,2,0,1,0,0,0
60640,57485453-52545749545698,0,0,0,0,0,0,0,2,0,0,0,0,0
60641,57485453-54565648545092,0,0,0,0,1,0,0,4,0,0,0,0,0
60642,57545549-57544957525799,0,0,0,0,0,1,0,0,0,0,0,0,0

In [ ]:
#data = pd.read_csv('MarketBusketFinal.csv', sep=';', encoding='utf-8-sig') 
MB = pd.read_csv('MBClient.csv', sep=';', encoding='utf-8-sig')

In [68]:
params = ["support", "confidence", "lift", "expected confidence"] 
res = pd.DataFrame(columns=params)

In [69]:
rows = [' + '.join(i) for i in itertools.permutations(columns, 2)] 
pairs = list(itertools.permutations(columns, 2))

In [70]:
print("Так выглядит список кобминаций, их " + str(len(rows)) + ", ниже приведён пример:\n") 
print(rows[1:5])

Так выглядит список кобминаций, их 156, ниже приведён пример:

['ДЕТСКОЕ ПИТАНИЕ + ИГРУШКИ', 'ДЕТСКОЕ ПИТАНИЕ + КАНЦТОВАРЫ, КНИГИ, ДИСКИ', 'ДЕТСКОЕ ПИТАНИЕ + КОСМЕТИКА/ГИГИЕНА', 'ДЕТСКОЕ ПИТАНИЕ + КРУПНОГАБАРИТНЫЙ ТОВАР']

In [71]:
temp = pd.DataFrame(0, index=[i for i in rows], columns=params) 

res = res.append(temp, ignore_index=False, sort=False) 
res = res.reset_index() 
res = res.rename(columns={"index": "Пара"}) 
res

/var/folders/sm/yw7wdqkn4jl9qbr7mwdtdxph0000gn/T/ipykernel_84132/1291965390.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res = res.append(temp, ignore_index=False, sort=False)

,Пара,support,confidence,lift,expected confidence
0,ДЕТСКОЕ ПИТАНИЕ + ЖЕНСКИЕ ШТУЧКИ,0,0,0,0
1,ДЕТСКОЕ ПИТАНИЕ + ИГРУШКИ,0,0,0,0
2,"ДЕТСКОЕ ПИТАНИЕ + КАНЦТОВАРЫ, КНИГИ, ДИСКИ",0,0,0,0
3,ДЕТСКОЕ ПИТАНИЕ + КОСМЕТИКА/ГИГИЕНА,0,0,0,0
4,ДЕТСКОЕ ПИТАНИЕ + КРУПНОГАБАРИТНЫЙ ТОВАР,0,0,0,0
...,...,...,...,...,...
151,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ПОДГУЗНИКИ,0,0,0,0
152,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + СОПУТСТВУЮЩИЕ ТОВАРЫ,0,0,0,0
153,"ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕКСТИЛЬ, ТРИКОТАЖ",0,0,0,0
154,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,0,0,0,0
155,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТОВАРЫ ДЛЯ ЖИВОТНЫХ,0,0,0,0

### Функции для рассчёта показателей

Support
Confidence
Expected confidence
Lift - данный показатель можно выразить через 2 другие функции, но для экономии вычислительного времени просто будем использовать полученные результаты и деление

In [72]:
def support(a, b, df):
    counter = 0
    for i in range(0, len(df)):
        if df[a][i] > 0 and df[b][i] > 0:
            counter += 1
    return counter/len(df)

In [73]:
def confidence(a, b, df):
    counter = 0
    total = 0
    for i in range(0, len(df)):
        if df[a][i] > 0:
            total += 1 
            if df[b][i] > 0:
                counter += 1
    return counter/total

In [74]:
def expconf(a, b, df):
    counter = 0
    for i in range(0, len(df)):
        if df[b][i] > 0:
            counter += 1
    return counter/len(df)

### Итоговая таблица

In [75]:
for i in range(0, len(pairs)): 
    sup = support(pairs[i][0], pairs[i][1], MB) 
    conf = confidence(pairs[i][0], pairs[i][1], MB) 
    exconf = expconf(pairs[i][0], pairs[i][1], MB) 
    lift = (conf / exconf) 
    res['support'][i] = sup 
    res['confidence'][i] = conf 
    res['expected confidence'][i] = exconf 
    res['lift'][i] = lift

In [76]:
res

,Пара,support,confidence,lift,expected confidence
0,ДЕТСКОЕ ПИТАНИЕ + ЖЕНСКИЕ ШТУЧКИ,0.000857,0.007227,2.213543,0.003265
1,ДЕТСКОЕ ПИТАНИЕ + ИГРУШКИ,0.030853,0.260042,0.733577,0.354484
2,"ДЕТСКОЕ ПИТАНИЕ + КАНЦТОВАРЫ, КНИГИ, ДИСКИ",0.008014,0.067547,1.302878,0.051844
3,ДЕТСКОЕ ПИТАНИЕ + КОСМЕТИКА/ГИГИЕНА,0.032403,0.273106,2.131804,0.12811
4,ДЕТСКОЕ ПИТАНИЕ + КРУПНОГАБАРИТНЫЙ ТОВАР,0.011856,0.099931,0.429671,0.232574
...,...,...,...,...,...
151,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ПОДГУЗНИКИ,0.052768,0.403989,1.57096,0.257161
152,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + СОПУТСТВУЮЩИЕ ТОВАРЫ,0.000759,0.005807,1.020797,0.005689
153,"ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕКСТИЛЬ, ТРИКОТАЖ",0.035519,0.271935,1.323513,0.205465
154,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,0.000297,0.002272,2.600143,0.000874
155,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТОВАРЫ ДЛЯ ЖИВОТНЫХ,0.002061,0.015781,0.810328,0.019475

In [77]:
res.to_csv('MBClientFinal.csv', index=False, sep=';', encoding='utf-8-sig')